db:
  build: mariadb10
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
php:
    build: php-fpm
    expose:
        - 9000:9000
    links:
        - db
    environment:
      MYSQL_PORT_3306_TCP_ADDR: db
      MYSQL_ENV_MYSQL_USER: root
      MYSQL_PASS: root
nginx:
    build: nginx
    ports:
        - 8000:8000
    links:
        - php
    volumes_from:
        - php
    volumes:
        - ./logs/nginx/:/var/log/nginx
